export const TABLE = {
    ADMIN: 'admin',
    USER: 'users',
    PRODUCT: 'products',
    SHIPPING_ADDRESS: 'shipping_addresses',
    ORDER: 'orders',
    ORDER_ITEM: 'order_items',
    CART_ITEM: 'cart_items',
    PRODUCT_VARIANT: 'product_variants',
    PAYMENT: 'payments',
    VARIANT: 'variants',
    CATEGORY: 'categories',
    PRODUCT_CATEGORIES: 'product_categories',
    GENERAL_SHIPPING: 'general_shipping',
    SHIPPING_METHODS: 'shipping_methods',
    SHIPPING_LOCATION_CONDITION: 'shipping_location_conditions',
    SHIPPING_FLAT_RATE_CONDITION: 'shipping_flat_rate_conditions',
    PAYMENT_OPTION: 'payment_options',
    SALES_LOCATION: 'sales_location',
    DISCOUNT: 'discounts',
    PRODUCT_DISCOUNT: 'product_discounts',
    REVIEW: 'reviews',
    RECENTLY_VIEW: 'recently_views',
    TAXES: 'taxes',
    BANNER: 'banners',
    CATEGORY_BANNER: 'category_banners',
    COUNTDOWN_BANNER: 'countdown_banners'
};