export const TABLE = {
    ADMIN: 'admin',
    USER: 'users',
    PRODUCT: 'products',
    SHIPPING_ADDRESS: 'shipping_addresses',
    ORDER: 'orders',
    ORDER_ITEM: 'order_items',
    CART_ITEM: 'cart_items',
    PRODUCT_VARIANT: 'product_variants',
    PAYMENT: 'payments',
    VARIANT: 'variants',
    CATEGORY: 'categories',
    PRODUCT_CATEGORIES: 'product_categories',
    GENERAL_SHIPPING: 'general_shipping',
    PAYMENT_OPTION: 'payment_options',
    SALES_LOCATION: 'sales_location',
    DISCOUNT: 'discounts',
    PRODUCT_DISCOUNT: 'product_discounts',
    COUNTRIES: 'countries',
    STATES: 'states',
    CITIES: 'cities',
};